version: "3.8"
services:
  nodeserver:
    build:
      context: ./
    ports:
      - "5001:5000"
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27019:27017
    volumes:
      - mongodb_data_container2:/data/db

volumes:
  mongodb_data_container2:
